---
title: "Przestrzenne bazy danych: porównanie bibliotek `spatstat` oraz `sp`"
author: 
    - Aleksandra Dzieniszewska
    - Eryk Warchulskki
output:
  html_notebook:
    toc: true
    toc_depth: 3
---


# Wprowadzenie 
## Zakres i cel projektu


Niniejszy projekt skupia się na porównaniu ze sobą dwóch biblotek dedykowanych danym przestrzennym w języku R, tj.:

* biblotece `spatstat` (w wersji `1.62-2 Shape-shifting lizard`)
* biblotece `sp` (w wersji `1.3-2`).


W projekcie zostaną porównane ze sobą reprezentacje danych przestrzennych przez obie bibloteki oraz ich zasób możliwości do

- wizualizacji
- przetwarzania
- transformacji układu współrzędnych 
- odczytu i zapisu danych.

W ramach przeprowadzonych porównań stosowane będą różne metryki -- od tych wyrażalnych liczbowo jak czas wykonania lub zajętość pamięci po subiektywne odczucia użytkownika. 


W sekcji pierwszej omówiona zostanie reprezentacja danych przestrzennych, która występuje w badanych pakietach, oraz zamieszczona jest tam krótka charakterystyka obu pakietów. Sekcja druga dotyczy kwestii zależności biblotek od biblotek zewnętrznych. Sekcja trzecia i czwarta omawia kolejno: metody wizualizacji oraz konstrukcje obiektów geometrycznych. Zbadany tam zostanie i omówiony zostanie czas wykonania oraz UX (ang. _user experience_). Sekcja piąta dotyczy transformacji układu współrzędnych, a sekcja szósta -- metod zapisu o dycztu danych.  Dokument zakończony jest podsumowaniem, wnioskami, płynącymi z użytkowania obu pakietów, oraz biblografią użytą przez autorów w ramach źródła informacji. 


# Biblioteki i kod


```{R}
library(magrittr)
library(sp)
library(rgdal)
library(spatstat)
library(tmap)

get_points = function(.num, .package) { 
    if(.package == "sp")
        sp::SpatialPoints(cbind(runif(.num), runif(.num)))
    else
        spatstat::ppp(x = runif(.num), y = runif(.num), xrange = c(0, 1), yrange = c(0, 1))
}


plot_points = function(.num, .package = "sp", .f=graphics::plot) { 
        get_points(.num, .package) %T>% .f()
        dev.off()
}


#` Benchmark funkcji .f(...)

do_benchmark = function(.f, ...) {
    microbenchmark::microbenchmark(.f(...)) %>%
        dplyr::transmute(time = time*10^(-6)) %>%
        dplyr::transmute(mean = mean(time),
                      median = median(time),
                      max = max(time),
                      min = min(time)) %>% 
        dplyr::slice(1)
}

```

# Reprezentacja danych 
## Biblioteka `spatstat`

Bibloteka `spatstat` stanowi zbiór funkcji dedykowanych danym przestrzennym. Dokumentacja bibloteki złożona jest z ponad $1700$ stron, co daje około $850$ różnych funkcji. Po samej liczbie dostępnych metod można dojść do wniosku, że pakiet ten oferuje znacznie więcej, niż konstrukcje, wizualizacje czy zapis/odczyt danych przestrzennych. `Spatstat` wspiera m.in.:

- eksploracyjną analizę danych
- modelowanie (wraz z audytem uzyskanych modeli) oraz wnioskowanie statystyczne 
- symulacje dwuwymiarowych procesów stochastycznych (t.zw. pól losowych).

W projekcie te aspekty pakietu nie zostaną omówione, ponieważ pakiet `sp` nie zawiera żadnych metod, które pozwalałyby realizować powyższe zagadnienia.


*Reprezentacja danych* w omawianym pakiecie opiera się na czterech klasach zaimplementowanych w prostym systemie obiektowości języka `R`, tj. w systemie `S3`. System ten opiera się na funkcjach generycznych i przez to różni się od systemów obiektowości spotykanych we współczesnych językach obiektowych lub wspierających obiektowość (`Java` lub `Python`) opartą na t.zw. _message-passing_. 

Klasy służące do reprezentacji obiektów przestrzennych w biblotece `spatstat` są następujące:

1. Klasa `ppp`
2. Klasa `owin`
3. Klasa `im`
4. Klasa `psp`

Poniżej zostanie scharakteryzowana każda z klas.

### ppp

Klasa `ppp` reprezentuje jeden z obiektów geometrycznych modelowanych przez system typów bibloteki `spatstat`, tj. zbiór punktów (na płaszczyźnie). 

Obiekt `ppp` tworzony jest przez konstruktor `spatstat::ppp()`, który przyjmuje jako parametry koordynaty przestrzenne (`x`, `y`) oraz -- opcjonalnie -- etykietki przyporządkowane punktom (`marks`). Na obiekty `marks` nałożona jest warunek bycia reprezentantem typu `factor` (typ podstawowy języka `R`, który służy do reprezentacji wielkości kategorycznych). Ponadto, z każdym obiektem `ppp` związane jest _okno_, w którym ten obiekt się znajduje, tj. dwuwymiarowa płaszczyzna. Konstruktor obiektu w przypadku braku specyfikacji okna (obiekt typu `owin` jest omawiany w następnej podsekcji) umieszcza punkty w oknie $[0, 1]^{2}$, a te których koordynaty przestrzenne wykraczają poza domyślny obszar -- usuwa. 

Z obiektami typu `ppp` związane są następujące funkcje:

* `spatstat::as.ppp()` 
* `spatstat::plot.ppp()`
* `spatstat::summary.ppp()`
* `spatstat::scapp()`


Sposób utworzenia i wykonywania pewnych operacji na tym typie prezentuje poniższy listing:


```{R}
points_number = 50

points = points_number %>% spatstat::ppp(x = runif(.), y = runif(.), xrange = c(0, 1), yrange = c(0, 1))

points 

points %>% summary()

points %>% plot("Punkty")
```


### owin

Klasa `owin` reprezentuje jeden z obiektów geometrycznych modelowanych przez system typów bibloteki `spatstat`, tj. dwuwymiarową płaszczyznę. 

Obiekt `owin` tworzony jest przez konstruktor `spatstat::owin()` i wyróżnia się trzy podtypy tego obiektu: 

* `rectangle` (prostokąt)
* `polygonal` (wielokąt)
* `mask` (macierz z wartościami w zbiorze ${0, 1}$)

Obiekty typu `owin` mogą przyjmować dowolny kształt, być wizualizowane bez naniesionych punktów oraz dostępne są specyficzne dla powierzchni metody jak:


* `spatstat::as.ppp()` 
* `spatstat::plot.ppp()`
* `spatstat::summary.ppp()`
* `spatstat::area.owin()` 
* `spatstat::aperimeter()` 
* `spatstat::adiameter.owin()`
* `spatstat::boundingbox()`

Sposób utworzenia i wykonywania pewnych operacji na tym typie prezentuje poniższy listing:

```{R}
window = spatstat::owin(xrange = c(0, 3), yrange = c(0, 5))

window %>% spatstat::area()

window %>% plot(main = "Okno")

```

### im

Klasa `im` reprezentuje dwuwymiarowy obraz złożony z pikseli. 

Obiekt `im` tworzony jest przez konstruktor `spatstat::im()`, który przyjmuje jako parametry wejściowe:

* macierz wartości `v` oraz jej wymiarowość `dim` 
* szerokość `xrange` oraz długość `yrange` okna, które obejmuje obraz 
* szerokość `xstep` oraz długość `ystep` piksela 
* wektor koordynatów określających centra pikseli `xcol` oraz `yrow`


 
 
Sposób utworzenia obiektu `im` prezentuje poniższy listing:


```{R}
value_mat = matrix(runif(100), nrow=30, ncol=40)

pixel_image = spatstat::im(value_mat) 

pixel_image %>% plot(main = 'Szum bialy')

```

### psp 

Klasa `psp` reprezentuje linię i jest typem pochodnym typu `ppp`. Obiekt `psp` tworzony jest przez konstruktor `spatstat::psp()`.

Sposób utworzenia powyższego typu prezentuje poniższy listing:

```{R}
segment_line = psp(x0 = runif(1), y0 = runif(1), x1 = runif(1), y1= runif(1), window=owin())

segment_line %>% plot(main="Linia")

```

## Bibloteka `sp`

Bibloteka `sp` jest pakietem funkcji dedykowanych ściśle pod wizualizacje oraz transformacje danych przestrzennych. Pakiet ten nie wspiera czynności dodatkowych, które można wykonywać na danych przestrzennych jak modelowanie lub przeprowadzenie symulacji. 

Oparty jest on na innym systemie klas niż pakiet `spatstat` -- na znacznie bardziej złożonym i formalnie ścisłym systemie `S4`. 

*Reprezentacja danych* w biblotece `sp` oparta jest na 7 klasach w wersji bez dodatkowych atrybutów numerycznych lub kategorycznych (np. `SpatialPoints`) lub z dodatkowymi atrybutami (np. `SpatialPointsDataFrame`). Ponadto, w proponowanym systemie klas przez `sp` istnieje klasa abstrakcyjna `Spatial`, która zawiera metadane wspólnego dla każdego obiektu geometrycznego tej bibloteki.

Poniżej zostaną omówione wszystkie dostępne klasy w wersji dodatkowych atrybutów z wyłączeniem klasy `SpatialPointsDataFrame`, co wynika z faktu bardzo podobnego sposobu konstruowania obiektów tego rodzaju przy użyciu standardowych konstruktorów.

### Spatial 

Klasa abstrakcyjna `Spatial` zawiera następujące metody abstrakcyjne: 

* `sp::dimensions()`
* `sp::bbox()`
* `sp::coordinates()`
* `sp::spplot()`
* `sp::dimensions()`


### SpatialPoints

Konstrukcja obiektu `SpatialPoints` odbywa się przy pomocy konstruktura `sp::SpatialPoints()`, który jako parametr wejściowy przyjmuje `coords`, będący macierzą (lub ramką danych `data.frame`) $n$-wymiarową.

W przypadku potrzeby konstrukcji obiektu z dodatkowymi danymi, tj. typów `Spatial_DataFrame`, konstruktor przyjmuje parametr `data`, będący obiektem typu `data.frame` o liczbie wierszy równej `coords`.


W pakiecie istnieje również klasa `SpatialMultiPoint`, która jest rozszerzeniem `SpatialPoints` o możliwość przechowywania koordynatów wielu punktów, tj. 

```{R}
SpatialMultiPoints(list(
                    cbind(rnorm(3, 10), rnorm(3, 10)), # koordynaty 1...
                    cbind(rnorm(5, 10), rnorm(5, 0)) # koordynaty 2...
                    ))
```

Utworzenie `SpatialPoints` prezentuje poniższy listing:

```{R}
coordinates = tibble::tibble(x1 = runif(10), x2 = runif(10), x3 = runif(10))

points = coordinates %>% sp::SpatialPoints()

points 

points %>% plot()

```


Natomiast utworzenie `SpatialPointsDataFrame` wygląda następująco:

```{R}
coordinates = tibble::tibble(x1 = runif(10), x2 = runif(10), x3 = runif(10))

random_data = tibble::tibble(height = runif(10), weight = runif(10), iq = runif(10))

points = coordinates %>% sp::SpatialPointsDataFrame(data = random_data)

points %>% summary()

points %>% spplot()

```

### Grids
Klasa `SpatialGrid` oraz `SpatialPixels` reprezentują obiekty geometryczne typu siatka/krata
przy czym obiekty klasy `SpatialGrid` nie przechowują koordynatów przestrzennych, a _cały_ obiekt siatki. 
Ponadto klasa `SpatialGridDataFrame` przechowuje w każdym wierszu dodatkowe atrybuty numeryczne lub kategoryczne na każdą komórkę siatki.

```{R}
grid_topology = sp::GridTopology(cellcentre.offset = c(1,1,2), cellsize=c(1,1,1), cells.dim = c(3,4,6))

grid_object = sp::SpatialGrid(grid_topology)

summary(grid_object)

grid_object %>% plot("Siatka")
```

### Line, Lines, SpatialLines

Obiekt klasy `Line` reprezentują łamaną, która jest tworzona przez podanie wektorów dwóch współprzędnych do konstruktura `sp::Line()`. W celu utworzenia obiektu, który daje się wizualizować należy wywołać konstruktor `sp::SpatialLines()`, który jako parametr wejściowy przyjmuje listę obiektów `sp::Lines()`, a ta z kolei tworzona jest z list obiektów typu `Line`. Możliwe jest również dodanie atrybutów w postaci ramki danych, aby utworzyć obiekt `SpatialLinesDataFrame`. 

Według autorów pakiet `sp` poza funkcjami do wizualizacji łamanych nie zawiera zbyt wiele użytecznych funkcji.

Poniższy listing prezentuje sposób utworzenia obiektu `SpatialLines`.

```{R}
l1 = cbind(c(1,2,3), c(3,2,2)) # koordynaty 

sp_line1 = sp::Line(l1)

sp_lines = sp::Lines(list(sp_line1), ID = "a")

sp_final_line = sp::SpatialLines(list(sp_lines))

sp_final_line %>% plot(main = "Linia <(1, 3), (2, 2), (3, 2)>")
```


### Polygon, Polygons, SpatialPolygons

Obiekt klasy `Polygon` służy do reprezentacji wielokątów i jest konstruowany w sposób podobny do obiektu typu `Line`, tj. podania wektorów koordynatów dla współrzędnej $x$ oraz $y$. Po utworzeniu obiektu typu `Polygon` tworzony jest obiekt `Polygons`, zawierający listę obiektów `Polygon` oraz obligatoryjny identyfikator obiektu.


```{R}
polygon = sp::Polygon(cbind(c(2,4,4,1,2),c(2,3,5,4,2))) 

polygons = sp::Polygons(list(polygon), ID = "polygon_102")

spatial_polygons = sp::SpatialPolygons(list(polygons))

spatial_polygons %>% plot(main = "Wielobok")
            
```

## Uwagi

Reprezentacja obiektów przestrzennych oferowana przez pakiet `sp` jest znacznie bogatsza oraz jest oparta na bardziej złożonym systemie klas, niż reprezentacja w pakiecie `spatstat`. 

Sposób tworzenia obiektów w obu bibliotekach jest do siebie dosyć zbliżony, tj. przez podanie koordynatów przestrzennych w postaci wektora liczb rzeczywistych. W tej kwestii na korzyść pakietu `sp` przemawia bardzo łatwy sposób tworzenia obiektów przestrzennych o wymiarowości większej niż dwa. Typy biblioteki `spatstat` jak np. `ppp` ograniczony jest wyłącznie do dwóch wymiarów. W najnowszych wersjach pakietu `spatstat` istnieje co prawda typ `pp3`, w którym można tworzyć punkty trójwymiarowe lub typ `ppx` dedykowany do obiektów wielowymiarowych z dodatkowym wymiarem czasu, lecz typ ofery przez pakiet `sp` jest znacznie bardziej naturalny.


Dosyć niewygodnym aspektem pakietu `spatstat` przy tworzeniu obiektów `ppp` jest konieczność specyfikowania płaszczyzny, w której punkty są zawarte. W przypadku, w którym użytkownik losuje punkty z rozkładu o nieograniczonym nośniku lewo- i/lub prawostronnie, taka konieczność specyfikacji jest uciążliwa. 
Wydaje się, że domyślne parametry obiektu `owin` powinny być zależne od minimalnych i maksymalnych parametrów obiektu `ppp`.

Na korzyść pakietu `sp` jest również sposób tworzenia łamanych, który jest intuicyjny i w nieznaczny sposób różni się od tworzenia obiektów `polygon`.

# Zależność od pakietów zewnętrznych

Istotnym aspektem pakietów tworzonych w ekosystemie języka `R` jest ich zależność od pakietów zewnętrznych. Przy czym im ta zależność jest mniejsza, tym jest lepiej. Związane jest to ściśle z faktem:

* częstym brakiem kompatybilności wstecznej między nowymi wersjami interpreta języka, a pakietami zewnętrznymi 
* braku aktualizacji pakietów przez ich twórców w przypadku nowej wersji interpretera lub zmiany API pakietu zewnętrznego.


Biblioteka `spatstat` zależy od następujących pakietów zewnętrznych:

- `stats`

- `graphics`

- `grDevices`

- `utils`

- `methods`

- `nlme`

- `rpart`

przy czym tylko pakiety `nlme` oraz `rpart` nie posiadają priorytetu *base* co oznacza, że nie muszą być ściśle kompatibylne z aktualną wersją interpretera. Ich aktualizacja lub jej brak może być źródłem błędów w działaniu pakietu. 

`Spatstat` ponadto sugeruje, aby zainstalowane były następujace pakiety zewnętrzne: `sm, maptools, gsl, locfit, spatial,`
`rpanel, tkrplot, RandomFields (>= 3.1.24.1), RandomFieldsUtils(>= 0.3.3.1), fftwtools (>= 0.9-8)`, co nie jest dziwne w kontekście liczby funkcji oferowanych przez pakiet, ale znacznie zwiększa prawdopodobieństwo wystąpienia błędu, który będzie ciężki do wykrycia i naprawienia przez użytkownika.

Biblioteka `sp` zależy wyłącznie od pakietu `methods`, który posiada priorytet *base*, oraz sugeruje użycie niewielu pakietów zewnętrznych, tj.:
`RColorBrewer, rgdal (>= 0.8-7), rgeos (>= 0.3-13), gstat, maptools, deldir`.

W obrębie pakietu `sp` pewnym uniedogodnieniem dla użytkowników systemu `macOS` w wersji `Maverick` lub starszej był brak możliwości instalacji pakietu `rgdal` (pakiet odpowiedzialny za operacje IO) oraz `rgeos` (pakiet odpowiedzialny za operacje topologiczne na geometriach) z oficjalnego repozytorium pakietów CRAN. 


## Uwagi 

Pakiet `sp` zawiera znacznie mniejszą liczbę pakietów zewnętrznyc od których uzależnione jest jego działanie, co znacznie zmniejsza ryzyko wystąpienia błędu z powodu braku kompatybilności.

# Wizualizacja danych przestrzennych

Oba pakiety implementują własną wersję generycznej funkcji `plot()`. W sekcji tej zostaną porównane implementacje tych funkcji pod kątem czasu działania dla różnych rozmiarów danych przestrzennych. Omówiona zostanie ponadto funkcja `sp::spplot()` oraz szereg specyficznych funkcji z pakietu `spatstat`, które służą do rysowania obiektów geometrycznych.

## Wydajność rysowania prostych obiektów geometrycznych

```{R}

#sp_benchmark = tibble::tibble(do_benchmark(plot_points, 10),
#                              do_benchmark(plot_points, 1000),
#                              do_benchmark(plot_points, 100000))

#sp_benchmark = tibble::tibble(do_benchmark(plot_points, 10, 'spatstat'),
#                              do_benchmark(plot_points, 1000, 'spatstat'),
#                              do_benchmark(plot_points, 100000, 'spatstat'))

sp_benchmark %<>% dplyr::mutate(points_num = c(10, 1000, 100000),
                                package = "sp")
spatstat_benchmark %<>% dplyr::mutate(points_num = c(10, 1000, 100000), 
                                      package = "spatstat")

bench_df = dplyr::bind_rows(sp_benchmark, spatstat_benchmark)

bench_df
```


## Rysowanie złozonych obiektów geometrycznych

Pakiet `sp` implementuję również funkcję `sp:spplot()`, która jest roszerzeniem generycznej funkcji `plot()` o możliwość kolorowania obiektów `Spatial` na podstawie atrybutów
umieszczonych w ramkach danych. Pakiet `spatstat` nie posiada takiej funkcjonalności.

Na podstawie funkcji oferowanej przez pakiety `sp` sprawdzimy w jaki sposób narysować mapę.


Przy użyciu pakietu `sp` wygląda to w następujący sposób:
```{R}
philly_crimes_sp <- rgdal::readOGR(dsn = "../data/PhillyCrimerate/", layer = "PhillyCrimerate", verbose = FALSE)
spplot(philly_crimes_sp, "homic_dens")
```

Powyższe operacje sprowadzają sie do wczytania danych zawartych w pliku z roszerzeniem `.shp`, który zawiera specyfikację geometrii oraz dodatkowych danych, które pozwalają na utworzenie obiektu przestrzennego.

```{R}
philly_crimes_sp %>% class()
```

W naszym przypadku wczytany dostał omawiany wcześniej obiekt `SpatialPolygonsDataFrame`. Funkcja `sp::splot()` jak zostało wspomniane wcześniej -- bierze pod uwagę wskazane atrybuty z ramek danych i uwzględnia je na wykresie w postaci heatmapy. 

Abstrahując opisu od sposobu wczytania powyższych danych w pakiecie `spatstat`, które będą przedmiotem jednej z następnych sekcji dokumentu, podobna wizualizacja przy użyciu funkcji generycznej dla tego pakietu wyglądałaby w następujący sposób:

Ekstrakcja okna z obiektu zewnętrznego:
```{R}
spatstat_owin = maptools::as.owin.SpatialPolygons(philly_crimes_sp) 
```
Ekstrakcja koordynatów przestrzennych z obiektu zewnętrznego
```{R}
coords = sp::coordinates(philly_crimes_sp)
```

Ekstrakcja danych
```{R}
data_frame <- as.data.frame(philly_crimes_sp)
``` 
Utworzenie obiektu ppp
```{R}
ppp_object = spatstat::ppp(x = coords[,1], y = coords[,2], window = spatstat_owin, marks = data_frame['homic_dens'])
plot(ppp_object)

```


Sposób utworzenia tego wykresu jest znacznie bardziej skomplikowany i co gorsze -- jego estetyka mocno odbiega od tego, co można w prosty sposób uzyskać przy pomocy funkcji 
`sp::spplot()`.


Jednakże pakiet `spatstat` zapewnia szereg typów wykresów, których w prosty sposób nie da się uzyskać, stosując wyłącznie funkcje pakietu `sp`. 

Przykładem takiego wykresu może być poniżej zaprezentowany wykres funkcji gęstości punktów na płaszczyźnie:

```{R}
dens_ppp <- density(ppp_object)

plot(dens_ppp)
```

lub wykres dzielący okno na kwadraty i zliczający punkty wewnątrz każdego kwadratu:

```{R}
quadr = spatstat::quadratcount(ppp_object, nx = 4, ny = 3)
plot(quadr)

```

## Uwagi

* wizualizacja w pakiecie `sp` jest znacznie łatwiejsza i co istotne w kontekście prezentacji danych -- estetyka funkcji `sp::spplot()` jest lepsza od archaicznie wyglądających metod pakietu `spatstat`
* metody oferowane przez pakiet `sp` do wizualizacji danych są ponadto średnio dwukrotnie szybsze.

# Transformacje układu współrzędnych

W języku `R` notacją używaną do opisu układu współrzędnych (dalej CRS) jest `proj4string` z biblioteki `PROJ.4`, która wygląda w następujący sposób:

```
+<arg>=<value>

```
Na przykład:
```
+init=epsg:4121 +proj=longlat +ellps=GRS80
+datum=GGRS87 +no_defs +towgs84=-199.87,74.79,246.62
```

Przy wczytywaniu danych w formacie `.shp` przy pomocy użytej już wcześniej funkcji `rgdal::readOGR()` informacje o CRS są dołączane automatycznie. 

Pakiet `sp` oferuje następujące metody związane z CRS:

- `sp::proj4string()`
- `sp::CRS()`
- `sp::spTransform()`


Sposób użycia poniższych funkcji prezentuje poniższy listing:

```{R}
philly_crimes_sp %>% sp::proj4string()
```

```{R}
new_philly_crimes_sp = philly_crimes_sp %>% sp::spTransform(CRS("+init=epsg:27561"))
```
Przed zmianą CRS na CRS definiowany przez `epsg` o indeksie $27561$:
```{R}
plot(philly_crimes_sp)
```
Po zmianie CRS:
```{R}
plot(new_philly_crimes_sp)

```
Pakiet `spatstat` *nie oferuje* możliwości operowania na CRS.

# Zapis i wczytanie danych

## Operacje wczytania danych

Biblioteka `sp` natywnie nie posiada funkcji, które służą do odczytu danych przestrzennych z plików. W celu wczytania danych do typów wprowadzanych przez pakiet stosowany
jest pakiet `rgdal`, który z kolei zapewnia dostęp do metod biblioteki `GDAL` (Geospatial Data Abstraction Library) napisanej w języku C oraz C++.


Operacje odczytu dostępne w tej bibliotece to:

- `rgdal::readOGR()`
- `rgdal::readGDAL()`

Funkcja `rgdal::readOGR()` służy do odczytu danych wektorowych (np. `SpatialPoints`), a funkcja `rgdal::readGDAL()` do odczytu obiektów typu `Grids`.


Jedyną metodą wczytywania danych, która zwraca obiekt biblioteki `spatstat`, jest `spatstat::scanpp()`. Metoda ta jest wrapperem na bazową metodę języka `R` do odczytywania danych w formacie kolumnowym (CSV), tj. `utils::read.table()`, która lokalizuje co najwyżej dwie kolumny z parametrami przestrzennymi, a resztę kolumn traktuję jako `marks` tworzonego obiektu.

W większości przypadków jedyną _sensowną_ metodą wczytywania danych przestrzennych w biblotece `spatstat` jest wczytywanie ich za pomocą biblioteki `sp`. Procedura taka została przeprowadzona przy opisie wizualizacji.

### Dostępne formaty danych -- pakiet `sp`

W związku z faktem, że biblioteka `rgdal` dostarcza wrapperów na funkcje z biblioteki `GDAL` dostępne są wszytkie formaty obsługiwane przez nią. Przy czym najważniejsze z nich to:

- `.shp`
- `.shx`
- `.dbf`

W plikach z foramtem `.shp` zapisana jest geometria wczytywanych danych. Pliki `.dbf` zawierają dane nieprzestrzenne, które dołączane są do obiektów w postaci ramek danych (np. `SpatialLinesDataFrame`), natomiast pliki `.shx` zawierają indeksy umożliwiające szybkie wyszukiwanie elementów składowych obiektów geometrycznych.

Sposób użycia opisanych metod prezentuje poniższy listing:

```{R}
philly_df <- rgdal::readOGR(dsn = "../data/Philly/", layer = "PhillyTotalPopHHinc") 

philly_df %>% class()
```

przy czym parametr `dsn` jest ścieżką do katalogu, w którym znajdują się dane, a `layer` jest nazwą pliku z roszerzeniem `.shp`.

### Dostępne formaty danych -- pakiet `spatstat`

Jedynym dostępnym formatem, który obsługuje biblioteka `spatstat` jest format CSV.

## Operacje zapisu danych

Biblioteka `sp` stosuje metody zapisu dostarczane przez bibliotekę `rgdal`, tj.:

- `rgdal::writeOGR()`
- `rgdal::writeGDAL()`

Metody te posiadają identyczny sposób użycia jak funkcje służące do wczytywania danych.

### Dostępne formaty danych -- biblioteka `sp`


Biblioteka `sp` zapisuje dane do formatów:

- `.shp`
- `.shx`
- `.dbf`

### Dostępne formaty danych -- biblioteka `spatstat`

Biblioteka `spatstat` nie zapewnia metod, które pozwalałyby zapisywać dane do pliku w formacie dedykowanym danym przestrzennym lub w ogólności -- typom obiektów geometrycznych zapewninaych przez siebie. 
Jedyną metodą za pomocą takie obiekty można zapisywać jest zapis obiektów do plików binarnych RDS.

# Wnioski końcowe

Zakres dokonywanego porównania wyznaczała biblioteka `sp` ze względu na jej wyspecjalizowane zastosowanie, które ogranicza się do wizualizacji i przetwarzania danych przestrzennych. Funkcje zapewnianie przez bibliotekę `spatstat` -- co zostało wspomniane już na wstępie raportu -- znacznie wykraczają poza ten zakres. 
Jednakże w kontekście tylko tych płaszczyzn, na których oba pakiety można było ze soba porównać -- biblioteka `spatstat` nie jest najlepszym wyborem. 

Wniosek taki wynika z faktu, że pakiet ten oferuje obiekty geometryczne o bardzo prostej reprezentacji i najwięcej uwagi poświęcone jest obiektom typu `ppp`. Dodatkowo interfejs do operowania na proponowanych przez siebie typach jest niewygodny ze względu na konieczność specyfikacji obiektu okna. 
Sposób wizulizacji, który dostarcza biblioteka, również odbiega od pewnego _state-of-the-art_ metod wizualizacyjnych ekosystemu `R` i nieznacznie różni sie od metod bazowych metod wizualizacyjnych. 
Na niekorzyść pakietu świadczy również fakt, że niewiele pakietów poświęconych wizualizacji lub przetwarzania danych przestrzennych współpracuje z obiektami tej biblioteki, a w szczególnie rążący jest brak obsługi standardów *ESRI*. 

W przypadku biblioteki `sp` sytuacja jest wręcz przeciwna. Pakiet ten mimo długiego czasu życia nadal jest aktywie rozwijany i aktualizowany, a stosowany system typów powszechnie wykorzystywany nawet przez nowoczesne pakiety jak `tmap`, który pozwala tworzyć mapy w bardzo wygodny i estetyczny sposób:


```{R}
tmap_mode("plot")
tm_shape(philly_crimes_sp, projection="longlat") + tm_polygons("homic_dens", style="quantile")
```



